apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: onazart/hello-gitops
  newTag: 64c329101b9bca6b182697f32a450e060573bda5
